-- No placeholder seed data.
--
-- Real officials and their careers/assets/judgments are populated by the scraper
-- pipeline (see scraper/), NOT by this seed file:
--   1. supabase start && supabase db reset   (creates the empty schema)
--   2. npm run scrape                          (writes scraper/out/<slug>.json review files)
--   3. review the JSON: confirm judgment identity, fill asset amounts, set approved:true
--   4. npm run scrape:import                   (upserts officials by slug + imports approved facts)
--
-- A db reset wipes imported data, so re-run steps 2–4 afterwards to repopulate.
